version: 2

aliases:
  # Workflow filters
  - &filter-only-release
    branches:
      ignore: /.*/
    tags:
      only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
  - &filter-not-release-or-master
    tags:
      ignore: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
    branches:
      ignore: master
  - &filter-only-master
    branches:
      only: master

defaults: &defaults
  working_directory: ~/kentik-app
  docker:
    - image: circleci/node:10.15.3-stretch

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: |
            PLUGIN_NAME=kentik-app
            npm install
            npm run build
            sudo apt-get install jq
            VERSION=`cat src/plugin.json|jq '.info.version'| sed s/\"//g`
            # create zip file
            cd ~
            echo "Creating ZIP"
            zip \
              -x ${PLUGIN_NAME}/.git/**\* \
              -x ${PLUGIN_NAME}/node_modules/**\* \
              -r /tmp/${PLUGIN_NAME}-${VERSION}.zip \
              ${PLUGIN_NAME}
            # create tar file
            echo "Creating TAR"
            tar \
              --exclude .git \
              --exclude ${PLUGIN_NAME}/node_modules \
              -cvf /tmp/${PLUGIN_NAME}-${VERSION}.tar \
              ${PLUGIN_NAME}
            gzip /tmp/${PLUGIN_NAME}-${VERSION}.tar
            # create artifacts
            mkdir -p ~/${PLUGIN_NAME}/artifacts
            mv /tmp/${PLUGIN_NAME}-${VERSION}.zip ~/${PLUGIN_NAME}/artifacts/
            mv /tmp/${PLUGIN_NAME}-${VERSION}.tar.gz ~/${PLUGIN_NAME}/artifacts/
          no_output_timeout: 5m
      - save_cache:
          name: Save NPM Package Cache
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm
      - persist_to_workspace:
          root: .
          paths:
            - artifacts
            - dist
      - store_artifacts:
          path: artifacts
      - store_artifacts:
          path: dist

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Test
          command: |
            npm install
            sudo npm install -g jest
            npm test

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters: *filter-only-master
      - test:
          requires:
            - build
          filters: *filter-only-master

  build-branches-and-prs:
    jobs:
      - build:
          filters: *filter-not-release-or-master
      - test:
          requires:
            - build
          filters: *filter-not-release-or-master
